services:
  neo4j:
    image: neo4j:latest
    volumes:
      - ${BULK_STORAGE}/neo4j/logs:/logs
      - ${BULK_STORAGE}/neo4j/import:/import
      - ${BULK_STORAGE}/neo4j/config:/config
      - ${BULK_STORAGE}/neo4j/data:/data
      - ${BULK_STORAGE}/neo4j/plugins:/plugins
      - ${BULK_STORAGE}/certs:/var/lib/neo4j/certificates
    environment:
      - NEO4J_AUTH=${USERN}/${PASSWD}
      - NEO4J_PLUGINS=["apoc", "genai", "bloom"]
      - NEO4J_server_bolt_tls__level=OPTIONAL
      - NEO4J_dbms_security_auth__enabled=false
      - NEO4J_dbms_ssl_policy_bolt_private_key=${MY_DNS_NAME}.key
      - NEO4J_dbms_ssl_policy_bolt_public_certificate=${MY_DNS_NAME}.crt
      - NEO4J_server_bolt_listen__address=${MY_DNS_NAME}/bolt/
      - NEO4J_server_bolt_advertised__address=${MY_DNS_NAME}/bolt/
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "${UI_PORT}:${UI_PORT}"  # Browser UI
      - "${BOLT_PORT}:${BOLT_PORT}"  # Bolt API port
    restart: unless-stopped
    networks:
      - homeserver
    profiles:
      - llm
    container_name: neo4j