services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${ETCD_STORAGE_DIR}:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
     - homeserver

  milvus:
    container_name: milvus
    image: milvusdb/milvus:v2.5.20-gpu
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      # - ./milvus.yaml:/milvus/configs/milvus.yaml 
      - ${MILVUS_STORAGE_DIR}:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              device_ids: ["0"]
    ports:
      - "19530:19530"
      - "9093:9091"
    networks:
     - homeserver
    depends_on:
      - "etcd"
      - "minio"

  milvusui:
    image: zilliz/attu:v2.5.3
    environment:
      MILVUS_URL: milvus:19530
      HOST_URL: https://${MY_DNS_NAME}/attu
      SERVER_NAME: localhost
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - "milvus"
    networks:
     - homeserver
    container_name: milvusui

networks:
  default:
    name: homeserver
