services:
  log:
    image: goharbor/harbor-log:v2.14.2
    container_name: harbor-log
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - ${HARBOR_REGISTRY_STORAGE}/var/log/harbor/:/var/log/docker/:z
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/common/config/log/logrotate.conf
        target: /etc/logrotate.d/logrotate.conf
        bind:
          create_host_path: true
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/common/config/log/rsyslog_docker.conf
        target: /etc/rsyslog.d/rsyslog_docker.conf
        bind:
          create_host_path: true
    ports:
      - 127.0.0.1:1514:10514
    networks:
      - homeserver
    profiles:
      - harbor

  registry:
    image: goharbor/registry-photon:v2.14.2
    container_name: registry
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - ${HARBOR_REGISTRY_STORAGE}/data/registry:/storage:z
      - ${HARBOR_REGISTRY_STORAGE}/common/config/registry/:/etc/registry/:z
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/data/secret/registry/root.crt
        target: /etc/registry/root.crt
        bind:
          create_host_path: true
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/common/config/shared/trust-certificates
        target: /harbor_cust_cert
        bind:
          create_host_path: true
    networks:
      - homeserver
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "registry"
    profiles:
      - harbor

  registryctl:
    image: goharbor/harbor-registryctl:v2.14.2
    container_name: registryctl
    env_file:
      - ${HARBOR_REGISTRY_STORAGE}/common/config/registryctl/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - ${HARBOR_REGISTRY_STORAGE}/data/registry:/storage:z
      - ${HARBOR_REGISTRY_STORAGE}/common/config/registry/:/etc/registry/:z
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/common/config/registryctl/config.yml
        target: /etc/registryctl/config.yml
        bind:
          create_host_path: true
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/common/config/shared/trust-certificates
        target: /harbor_cust_cert
        bind:
          create_host_path: true
    networks:
      - homeserver
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "registryctl"
    profiles:
      - harbor

  postgresql:
    image: goharbor/harbor-db:v2.14.2
    container_name: harbor-db
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - ${HARBOR_REGISTRY_STORAGE}/data/database:/var/lib/postgresql/data:z
    networks:
      homeserver:
    env_file:
      - ${HARBOR_REGISTRY_STORAGE}/common/config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "postgresql"
    shm_size: '1gb'
    profiles:
      - harbor

  core:
    image: goharbor/harbor-core:v2.14.2
    container_name: harbor-core
    env_file:
      - ${HARBOR_REGISTRY_STORAGE}/common/config/core/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    volumes:
      - ${HARBOR_REGISTRY_STORAGE}/data/ca_download/:/etc/core/ca/:z
      - ${HARBOR_REGISTRY_STORAGE}/data/:/data/:z
      - ${HARBOR_REGISTRY_STORAGE}/common/config/core/certificates/:/etc/core/certificates/:z
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/common/config/core/app.conf
        target: /etc/core/app.conf
        bind:
          create_host_path: true
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/data/secret/core/private_key.pem
        target: /etc/core/private_key.pem
        bind:
          create_host_path: true
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/data/secret/keys/secretkey
        target: /etc/core/key
        bind:
          create_host_path: true
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/common/config/shared/trust-certificates
        target: /harbor_cust_cert
        bind:
          create_host_path: true
    networks:
      homeserver:
    depends_on:
      - log
      - registry
      - redis
      - postgresql
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "core"
    profiles:
      - harbor

  portal:
    image: goharbor/harbor-portal:v2.14.2
    container_name: harbor-portal
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/common/config/portal/nginx.conf
        target: /etc/nginx/nginx.conf
        bind:
          create_host_path: true
    networks:
      - homeserver
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "portal"
    profiles:
      - harbor

  jobservice:
    image: goharbor/harbor-jobservice:v2.14.2
    container_name: harbor-jobservice
    env_file:
      - ${HARBOR_REGISTRY_STORAGE}/common/config/jobservice/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - ${HARBOR_REGISTRY_STORAGE}/data/job_logs:/var/log/jobs:z
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/common/config/jobservice/config.yml
        target: /etc/jobservice/config.yml
        bind:
          create_host_path: true
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/common/config/shared/trust-certificates
        target: /harbor_cust_cert
        bind:
          create_host_path: true
    networks:
      - homeserver
    depends_on:
      - core
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "jobservice"
    profiles:
      - harbor

  redis:
    image: goharbor/redis-photon:v2.14.2
    container_name: redis
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - ${HARBOR_REGISTRY_STORAGE}/data/redis:/var/lib/redis
    networks:
      homeserver:
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "redis"
    profiles:
      - harbor

  proxy:
    image: goharbor/nginx-photon:v2.14.2
    container_name: nginx
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - ${HARBOR_REGISTRY_STORAGE}/common/config/nginx:/etc/nginx:z
      - type: bind
        source: ${HARBOR_REGISTRY_STORAGE}/common/config/shared/trust-certificates
        target: /harbor_cust_cert
        bind:
          create_host_path: true
    networks:
      - homeserver
    ports:
      - 8081:8080
    depends_on:
      - registry
      - core
      - portal
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "proxy"
    profiles:
      - harbor