services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - ${JENKINS_STORAGE}:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--prefix=/jenkins" # Optional: for sub-path access
      - VIRTUAL_HOST=${MY_DNS_NAME}
    networks:
      - homeserver
    container_name: jenkins
    profiles:
      - cicd

  ssh-agent:
    image: jenkins/ssh-agent
    networks:
      - homeserver
    container_name: jenkins-ssh-agent
    profiles:
      - cicd