receivers:
  kafkametrics:
    brokers: kafka:29092
    protocol_version: 2.0.0
    scrapers:
      - brokers
      - topics
      - consumers
      - producer
      - messages
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:8888']

  otlp:
    protocols:
      grpc:
      http:

exporters:

service:
  pipelines:
    metrics:
      receivers: [otlp,kafkametrics,prometheus]
      processors: [batch]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    logs:
      receivers: [otlp,kafkametrics,prometheus]
      processors: [batch]
      exporters: [otlphttp]