services:
  redis_home:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379 
    volumes:
      - ${REDIS_PERSISTENT_STORAGE}:/data
    networks:
     - homeserver
    depends_on:
     - kafka
    profiles:
      - etl
    container_name: redis_home
